Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2019-08, with the labels that each got.

#114 Update sidam config
  src/main/resources/application.yaml
Labels: ns:sscs-ccd-callback-orchestrator-pr-114

#122 SSCS-6255 Reference data – Update sscs-venues.csv (change needed by 1…
  build.gradle
Labels: ns:sscs-ccd-callback-orchestrator-pr-122

#120 SSCS-6264 - update sscs-common version
  build.gradle
Labels: ns:sscs-ccd-callback-orchestrator-pr-120

#126 remove deprecated config
  Jenkinsfile_CNP
Labels: ns:sscs-ccd-callback-orchestrator-pr-126
