Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2020-09, with the labels that each got.

#363 Update security alert level to medium
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-363

#377 Upgrade terraform
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-377

#376 SSCS-8118: Notifications – Multiple notifications are being sent out
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorControllerTest.java
  src/functionalTest/resources/validAppealCreatedCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/Application.java
  src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorController.java
  src/test/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorControllerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-376

#390 WLA-735: Update commons
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-390

#394 Bump common 3.5.0
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-394
