Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2020-08, with the labels that each got.

#343 Nightly functional tests
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-343

#344 Update nightly test product
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-344

#346 SSCS-7535 up common for isScottish
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-346

#360 Remove unused tf remote state
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-360
