Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2021-12, with the labels that each got.

#778 spring dependency check modified
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-778

#782 Upgrade log4j to 2.15.0
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-782

#786 SSCS-9743:Child Support - otherPartyAdded Notification
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-786
