Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-09, with the labels that each got.

#946 SSCS-10818 Commons Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-946

#948 SSCS-10901 Configure renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-948

#949 SSCS-10901 Fix renovate json
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-949

#947 SSCS-10882 Fixing Conflicting IDs
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-947
