Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-04, with the labels that each got.

#856 SSCS Commons 4.7.1 Upgrade
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-856

#873 10376 upgrade branch
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-873

#879 Don't allow miss match versions
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-879

#858 sscs-10146 update sscs-common RC version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-858

#870 SSCS-10387 Update Commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-870
