Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-02, with the labels that each got.

#813 update sscs-common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-813

#828 surppress dependencies
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-828

#829 upgrade helm chart
  charts/sscs-ccd-callback-orchestrator/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-829

#830 update sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-830

#833 upgrading log4j to 2.17.1
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-833
