Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-07, with the labels that each got.

#924 SSCS-10706 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-924

#929 SSCS-10087 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-929

#928 sscsBaseChartUpdate-Java401
  charts/sscs-ccd-callback-orchestrator/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-928
