Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-10, with the labels that each got.

#963 SSCS-10985 CVE Fix Commons Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-963

#971 Commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-971

#972 SSCS-11063 Use Renovate Shared Preset
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-972

#962 SSCS-10924 Move to tf managed secret.
  charts/sscs-ccd-callback-orchestrator/Chart.yaml
  charts/sscs-ccd-callback-orchestrator/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-962
