Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-08, with the labels that each got.

#932 extend-suppression-dates
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-932

#933 SSCS-10805-jar-version-update
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-933

#938 SSCS-10773: Update commons version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-938

#943 chore: increment sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-943

#937 SSCS-9874-common-version-update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-937

#944 Add backstage configuration file
  catalog-info.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-944

#945 SSCS-10841 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-945
