Repository hmcts/sscs-ccd-callback-orchestrator, pull requests merged in 2022-05, with the labels that each got.

#882 SSCS-10223 Model bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-882

#867 SSCS-10388 Update Commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-867

#883 SSCS-10444 Change CVE Reporting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-883

#886 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-886

#895 SSCS-10552: upgrade tomcat
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-895

#896 SSCS-10116 Bump SSCS Commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-896

#898 SSCS-10561: Updating spring and suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-ccd-callback-orchestrator-pr-898
